import { test, expect } from '@playwright/test'
test('core loop: home → category → project → all projects → home', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()}: ${response.url()}`) })
  await page.goto('/')
  const background = page.locator('.home-video')
  await expect(background).toHaveAttribute('loop', '')
  await expect.poll(() => background.evaluate((v: HTMLVideoElement) => v.readyState)).toBeGreaterThanOrEqual(2)
  await expect.poll(() => background.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Pause background' }).click()
  await expect.poll(() => background.evaluate((v: HTMLVideoElement) => v.paused)).toBe(true)
  await page.getByRole('link', { name: 'Branding', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Branding', exact: true })).toBeVisible()
  await expect(page.locator('.project-card')).toHaveCount(3)
  await page.getByRole('link', { name: /eggy project preview/ }).click()
  await expect(page.getByRole('heading', { name: 'eggy', exact: true })).toBeVisible()
  await expect(page.getByText('An escape plan to escape stereotypes')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Idea', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'eggy', exact: true })).toBeVisible()
  await page.getByRole('link', { name: /Browse more projects/ }).click()
  await expect(page.locator('.project-card')).toHaveCount(6)
  await page.getByRole('link', { name: /Glimmera project preview/ }).click()
  await expect(page.getByText('Disney Imagination Competition 2025 · Finalists', { exact: false })).toBeVisible()
  await page.getByRole('link', { name: /Browse more projects/ }).click()
  await page.getByRole('link', { name: /From the Ground/ }).click()
  await expect(page.getByRole('heading', { name: 'Stay tuned.' })).toBeVisible()
  await page.getByRole('link', { name: /d.archivol — home/ }).click()
  await page.getByRole('link', { name: 'Entertainment Concept', exact: true }).click()
  await expect(page.locator('.project-card')).toHaveCount(3)
  await page.getByRole('link', { name: /The Unseen Marine project preview/ }).click()
  await expect(page.getByRole('heading', { name: 'The Dinner', exact: true })).toBeVisible()
  await page.getByRole('link', { name: /Browse more projects/ }).click()
  await page.getByRole('link', { name: /gutter project preview/ }).click()
  await page.getByText('The Interactive System', { exact: true }).click()
  await expect(page.getByText('From encountering Gutter in the supermarket', { exact: false })).toBeVisible()
  await page.getByRole('link', { name: /Browse more projects/ }).click()
  await page.getByRole('link', { name: /白夜製作 project preview/ }).click()
  await expect(page.getByRole('heading', { name: 'The Brief' })).toBeVisible()
  await page.getByRole('link', { name: /d.archivol — home/ }).click()
  await page.getByRole('link', { name: 'Graphic Design', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Stay tuned.' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: /d.archivol — home/ }).click()
  await expect(page.getByRole('navigation', { name: 'Project categories' })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  await expect(page.getByRole('button', { name: 'Play background' })).toBeVisible()
  await expect.poll(() => page.locator('.home-video').evaluate((v: HTMLVideoElement) => v.paused)).toBe(true)
  expect(errors).toEqual([])
})
